

CREATE TABLE Clientes(
	ClienteID INT IDENTITY(1,1) PRIMARY KEY,
	Nombre NVARCHAR(150) NOT NULL,
	Email NVARCHAR(150) NOT NULL,
	FechaRegistro DATETIME NULL DEFAULT GETDATE(),  
	Estado BIT NOT NULL DEFAULT 1
);
GO

CREATE TABLE Productos(
	ProductoID INT IDENTITY(1,1) PRIMARY KEY,
	Nombre NVARCHAR(150) NOT NULL,
	Descripcion NVARCHAR(300) NOT NULL,
	Precio DECIMAL(10,2) NOT NULL,  
	Stock INT NOT NULL,
	Estado BIT NOT NULL DEFAULT 1
);
GO

CREATE TABLE Pedidos(
	PedidoID INT IDENTITY(1,1) PRIMARY KEY,
	CLienteID INT NOT NULL,
	FechaPedido DATETIME NOT NULL DEFAULT GETDATE(),
	Total DECIMAL(10,2) NOT NULL DEFAULT 0,
	Estado NVARCHAR(20) NOT NULL DEFAULT 'CREADO'
); 
GO

CREATE TABLE DetallePedidos(
	DetalleID INT IDENTITY(1,1) PRIMARY KEY,
	PedidoID INT NOT NULL,
	ProductoID INT NOT NULL,
	Cantidad INT NOT NULL,
	PrecioUnitario DECIMAL(10,2) NOT NULL,
	Subtotal AS (Cantidad * PrecioUnitario) PERSISTED 
);
GO